// Generated by https://pagedraw.io/pages/11065
import React from 'react';
import './component.css';


function render() {
    return <div className="component-component-0">
        <div className="component-0">
            <div className="component-popular_playlists-0">
                Popular playlists
            </div>
        </div>
        <div className="component-1">
            <div className="component-rectangle_2" /> 
            <div className="component-rectangle_2_" /> 
            <div className="component-rectangle_2_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
