// Generated by https://pagedraw.io/pages/11065
import React from 'react';
import './google_pixel_2_xl.css';


function render() {
    return <div className="google_pixel_2_xl-google_pixel_2">
        <div className="google_pixel_2_xl-0">
            <div className="google_pixel_2_xl-rectangle-0">
                <div className="google_pixel_2_xl-0-0-0">
                    <div className="google_pixel_2_xl-home-0">Home</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
